#just for tac
statistics=true
job=SEQ_PROJET
jobVersion=0.1
date=2026-03-03 211750784
contextName=rec
jobId=_ML_I0BMHEfGX1IjHrOgGxg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=BI_MY_SYSTEM
branch=branches/
cmdLineVersion=202511
gitAuthor=
gitCommitId=
gitCommitDate=