#this is context properties
#Tue Mar 03 22:17:33 CET 2026
SA_V1_Password=enc\:routine.encryption.key.v1\:d1bcEjG/U7Vr1nCTyi7dWK8k8JfmAo3rJitqB+s40Vv+DdvjZTVYbKBSROh11NYr1j/sSQ\=\=
SA_V1_Server=localhost
SA_V1_Port=1433
SA_V1_Login=bi_fms
SA_V1_AdditionalParams=
SA_V1_Schema=sa
SA_V1_Database=bi_fms_mysystem
JOURNAL_Database=bi_fms_mysystem
JOURNAL_Schema=journal
JOURNAL_Server=localhost
JOURNAL_AdditionalParams=
JOURNAL_Port=1433
JOURNAL_Login=bi_fms
JOURNAL_password=enc\:routine.encryption.key.v1\:SmkWuI+eeYAg5a7aXHWLMbq1hifN3CdS/+qRP3ujTk9T6X1ZAgUseMeBbKVqghXu0kRskg\=\=
ODS_V1_Server=localhost
ODS_V1_Schema=ods
ODS_V1_Login=bi_fms
ODS_V1_AdditionalParams=
ODS_V1_Database=bi_fms_mysystem
ODS_V1_Password=enc\:routine.encryption.key.v1\:aT3H6JIB0IXhizO+1NMbq6/kQfEpsc8kR47KwJASJgRCtS+9gqg5mbujk+Bjx0BTIaFGlg\=\=
ODS_V1_Port=1433
