#this is context properties
#Tue Mar 03 22:17:33 CET 2026
DWH_V1_AdditionalParams=
DWH_V1_Database=bi_fms_mysystem
DWH_V1_Login=bi_fms
DWH_V1_Password=enc\:routine.encryption.key.v1\:O02uuxJGEMPdU5BiYsYHsBASHr3OsmJzqX1Lc2xHKhYAUZqNrfHfNNa7K+PqjqkRYjeHAg\=\=
DWH_V1_Port=1433
DWH_V1_Schema=dwh
DWH_V1_Server=localhost
JOURNAL_AdditionalParams=
JOURNAL_Database=bi_fms_mysystem
JOURNAL_Login=bi_fms
JOURNAL_password=enc\:routine.encryption.key.v1\:h3I5+fi0ayVv4Jete1eKFNr++tYR3LIdXOnhzHMKOrd907UJOewpjCGbB6vYwndP3yk/lQ\=\=
JOURNAL_Port=1433
JOURNAL_Schema=journal
JOURNAL_Server=localhost
ODS_V1_AdditionalParams=
ODS_V1_Database=bi_fms_mysystem
ODS_V1_Login=bi_fms
ODS_V1_Password=enc\:routine.encryption.key.v1\:W0+8YVC6cfG1t6b4qZmRUYXHn+qKyPvVNS7Ljw+JopB4ztyWlqF7qrLVCxj6tKy9LQSCJA\=\=
ODS_V1_Port=1433
ODS_V1_Schema=ods
ODS_V1_Server=localhost
SA_V1_AdditionalParams=
SA_V1_Database=bi_fms_mysystem
SA_V1_Login=bi_fms
SA_V1_Password=enc\:routine.encryption.key.v1\:+iP3sU63HkcFLQ3cPo73FmpMSaRl0z4kCuX3+Jr1upZturW8QjJe+MunHY9LtVq6idHb8Q\=\=
SA_V1_Port=1433
SA_V1_Schema=sa
SA_V1_Server=localhost
environnement=DEV-TEST
