#this is context properties
#Tue Mar 03 22:17:32 CET 2026
JOURNAL_password=enc\:routine.encryption.key.v1\:nOU9KA3Zk5/9rrX8cV0dxYKpioRsyKqfYOw9eYOKrLm2zP7nZ9FHOuoFl2/vZInwWGGD6A\=\=
JOURNAL_Server=localhost
JOURNAL_AdditionalParams=
JOURNAL_Schema=journal
JOURNAL_Login=bi_fms
JOURNAL_Port=1433
JOURNAL_Database=bi_fms_mysystem
DWH_V1_Port=1433
DWH_V1_Server=localhost
DWH_V1_Login=bi_fms
DWH_V1_AdditionalParams=
DWH_V1_Schema=dwh
DWH_V1_Database=bi_fms_mysystem
DWH_V1_Password=enc\:routine.encryption.key.v1\:QKk3K2uZ6ahrOVN7RiBJ7iIktNmw1sSbqOsMCSn/g4timdmEuJvRmknfPt30IMtJLh/Z6Q\=\=
SA_V1_Login=bi_fms
SA_V1_Port=1433
SA_V1_AdditionalParams=
SA_V1_Schema=sa
SA_V1_Database=bi_fms_mysystem
SA_V1_Password=enc\:routine.encryption.key.v1\:VPTtDJNoFHFDb3fWjXHLajTvCXCNC5OOmDhkkTVa71kRsuPuWWEj2eMgtuuniWxKPbCvlQ\=\=
SA_V1_Server=localhost
