#this is context properties
#Tue Mar 03 22:17:32 CET 2026
JOURNAL_password=enc\:routine.encryption.key.v1\:oI4P8p5+nvQDYM4sOhZt/y/Ijci32q88FebAfRWMXgCC1O1x3QjELtce1Nt1teVlRWvkNA\=\=
JOURNAL_Server=localhost
JOURNAL_AdditionalParams=
JOURNAL_Schema=journal
JOURNAL_Login=bi_fms
JOURNAL_Port=1433
JOURNAL_Database=bi_fms_mysystem
DWH_V1_Port=1433
DWH_V1_Server=localhost
DWH_V1_Login=bi_fms
DWH_V1_AdditionalParams=
DWH_V1_Schema=dwh
DWH_V1_Database=bi_fms_mysystem
DWH_V1_Password=enc\:routine.encryption.key.v1\:1Yj46i16IpSTbPu90YOkxqwaWwSvpqFOx3TiB6OtmphCUQnU2zwgIdLW/GjbdDs0ctEwxg\=\=
SA_V1_Login=bi_fms
SA_V1_Port=1433
SA_V1_AdditionalParams=
SA_V1_Schema=sa
SA_V1_Database=bi_fms_mysystem
SA_V1_Password=enc\:routine.encryption.key.v1\:IycMen6jzsoypf8qXqsZDIQVoRECV2RaZev92rxlOFfI7cJxiHUlveS/qi0HeSOEumQ3Ug\=\=
SA_V1_Server=localhost
